import path from "path";
import fs from "fs";
import { execAsync } from "../../../utils/exec.js";
import { env } from "../../config/env.js";

export async function generateAngularProject(name) {
  const projectPath = path.join(env.PROJECTS_DIR, name);

  if (fs.existsSync(projectPath)) {
    throw new Error(`Project '${name}' already exists`);
  }

  // 1. Create Angular project using CLI
  await execAsync(`ng new ${name} --routing --style=scss --skip-git`, {
    cwd: env.PROJECTS_DIR
  });

  // 2. Add a README
  fs.writeFileSync(
    path.join(projectPath, "README.md"),
    `# ${name}\n\nGenerated by Project Wizard\n`
  );

  return {
    name,
    path: projectPath,
    type: "angular",
    createdAt: new Date().toISOString()
  };
}
