import path from "path";
import fs from "fs";
import { execAsync } from "../../../utils/exec.js";
import { env } from "../../config/env.js";

export async function generateNodeProject(name) {
  const projectPath = path.join(env.PROJECTS_DIR, name);

  if (fs.existsSync(projectPath)) {
    throw new Error(`Project '${name}' already exists`);
  }

  // 1. Create project folder
  fs.mkdirSync(projectPath);

  // 2. Initialize npm project
  await execAsync(`npm init -y`, {
    cwd: projectPath
  });

  // 3. Install dependencies
  await execAsync(`npm install express cors dotenv`, {
    cwd: projectPath
  });

  // 4. Create src folder structure
  const srcPath = path.join(projectPath, "src");
  const routesPath = path.join(srcPath, "routes");
  const controllersPath = path.join(srcPath, "controllers");

  fs.mkdirSync(srcPath);
  fs.mkdirSync(routesPath);
  fs.mkdirSync(controllersPath);

  // 5. Create index.js
  fs.writeFileSync(
    path.join(srcPath, "index.js"),
    `
import express from "express";
import cors from "cors";
import dotenv from "dotenv";

import healthRouter from "./routes/health.routes.js";

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json());

app.use("/health", healthRouter);

const PORT = process.env.PORT || 3000;

app.listen(PORT, () => {
  console.log("${name} API running on port " + PORT);
});
`.trim()
  );

  // 6. Create health route
  fs.writeFileSync(
    path.join(routesPath, "health.routes.js"),
    `
import express from "express";
import { HealthController } from "../controllers/health.controller.js";

const router = express.Router();

router.get("/", HealthController.status);

export default router;
`.trim()
  );

  // 7. Create health controller
  fs.writeFileSync(
    path.join(controllersPath, "health.controller.js"),
    `
export const HealthController = {
  status(req, res) {
    res.json({
      status: "ok",
      service: "${name}",
      timestamp: new Date().toISOString()
    });
  }
};
`.trim()
  );

  // 8. Add README
  fs.writeFileSync(
    path.join(projectPath, "README.md"),
    `# ${name}\n\nGenerated by Project Wizard\n`
  );

  return {
    name,
    path: projectPath,
    type: "node",
    createdAt: new Date().toISOString()
  };
}
