import path from "path";
import fs from "fs";
import { execAsync } from "../../../utils/exec.js";
import { env } from "../../config/env.js";

export async function generateReactProject(name) {
  const projectPath = path.join(env.PROJECTS_DIR, name);

  if (fs.existsSync(projectPath)) {
    throw new Error(`Project '${name}' already exists`);
  }

  // 1. Create React project using Vite
  await execAsync(`npm create vite@latest ${name} -- --template react`, {
    cwd: env.PROJECTS_DIR
  });

  // 2. Install dependencies
  await execAsync(`npm install`, {
    cwd: projectPath
  });

  // 3. Add a README
  fs.writeFileSync(
    path.join(projectPath, "README.md"),
    `# ${name}\n\nGenerated by Project Wizard\n`
  );

  return {
    name,
    path: projectPath,
    type: "react",
    createdAt: new Date().toISOString()
  };
}
